### PR TITLE
feat: support for S3 Transfer Acceleration

### PR DESCRIPTION
**Pull request by nikolay**
Resolves trussworks/terraform-aws-s3-private-bucket#345

### CODE REVIEW

**Review by ralren — APPROVED** [review]

**Comment by rpdelaney** [comment]
@nikolay Are you able to address the merge conflicts? Then we should be able to get this merged in. Thank you!

**Comment by nikolay** [comment]
@rpdelaney Sorry, I had to force-push - now it's using your `main` branch. I also did some restyling for better readability, if you don't mind.

**Comment by rpdelaney** [comment]
Thank you!

**Comment by rpdelaney** [comment]
Released in `v4.2.0`

**Pull request merged**
